/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignalsIndexRouteImport } from './routes/signals.index'
import { Route as BriefingsIndexRouteImport } from './routes/briefings.index'
import { Route as SignalsItemIdRouteImport } from './routes/signals.$itemId'
import { Route as BriefingsDigestIdRouteImport } from './routes/briefings.$digestId'
import { Route as ApiItemsRouteImport } from './routes/api.items'
import { Route as ApiDigestsRouteImport } from './routes/api.digests'
import { Route as ApiItemsIdRouteImport } from './routes/api.items.$id'
import { Route as ApiDigestsIdRouteImport } from './routes/api.digests.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsIndexRoute = SignalsIndexRouteImport.update({
  id: '/signals/',
  path: '/signals/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsIndexRoute = BriefingsIndexRouteImport.update({
  id: '/briefings/',
  path: '/briefings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsItemIdRoute = SignalsItemIdRouteImport.update({
  id: '/signals/$itemId',
  path: '/signals/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsDigestIdRoute = BriefingsDigestIdRouteImport.update({
  id: '/briefings/$digestId',
  path: '/briefings/$digestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsRoute = ApiItemsRouteImport.update({
  id: '/api/items',
  path: '/api/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestsRoute = ApiDigestsRouteImport.update({
  id: '/api/digests',
  path: '/api/digests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsIdRoute = ApiItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiItemsRoute,
} as any)
const ApiDigestsIdRoute = ApiDigestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDigestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/digests': typeof ApiDigestsRouteWithChildren
  '/api/items': typeof ApiItemsRouteWithChildren
  '/briefings/$digestId': typeof BriefingsDigestIdRoute
  '/signals/$itemId': typeof SignalsItemIdRoute
  '/briefings/': typeof BriefingsIndexRoute
  '/signals/': typeof SignalsIndexRoute
  '/api/digests/$id': typeof ApiDigestsIdRoute
  '/api/items/$id': typeof ApiItemsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/digests': typeof ApiDigestsRouteWithChildren
  '/api/items': typeof ApiItemsRouteWithChildren
  '/briefings/$digestId': typeof BriefingsDigestIdRoute
  '/signals/$itemId': typeof SignalsItemIdRoute
  '/briefings': typeof BriefingsIndexRoute
  '/signals': typeof SignalsIndexRoute
  '/api/digests/$id': typeof ApiDigestsIdRoute
  '/api/items/$id': typeof ApiItemsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/digests': typeof ApiDigestsRouteWithChildren
  '/api/items': typeof ApiItemsRouteWithChildren
  '/briefings/$digestId': typeof BriefingsDigestIdRoute
  '/signals/$itemId': typeof SignalsItemIdRoute
  '/briefings/': typeof BriefingsIndexRoute
  '/signals/': typeof SignalsIndexRoute
  '/api/digests/$id': typeof ApiDigestsIdRoute
  '/api/items/$id': typeof ApiItemsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/digests'
    | '/api/items'
    | '/briefings/$digestId'
    | '/signals/$itemId'
    | '/briefings/'
    | '/signals/'
    | '/api/digests/$id'
    | '/api/items/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/digests'
    | '/api/items'
    | '/briefings/$digestId'
    | '/signals/$itemId'
    | '/briefings'
    | '/signals'
    | '/api/digests/$id'
    | '/api/items/$id'
  id:
    | '__root__'
    | '/'
    | '/api/digests'
    | '/api/items'
    | '/briefings/$digestId'
    | '/signals/$itemId'
    | '/briefings/'
    | '/signals/'
    | '/api/digests/$id'
    | '/api/items/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDigestsRoute: typeof ApiDigestsRouteWithChildren
  ApiItemsRoute: typeof ApiItemsRouteWithChildren
  BriefingsDigestIdRoute: typeof BriefingsDigestIdRoute
  SignalsItemIdRoute: typeof SignalsItemIdRoute
  BriefingsIndexRoute: typeof BriefingsIndexRoute
  SignalsIndexRoute: typeof SignalsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/': {
      id: '/signals/'
      path: '/signals'
      fullPath: '/signals/'
      preLoaderRoute: typeof SignalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/': {
      id: '/briefings/'
      path: '/briefings'
      fullPath: '/briefings/'
      preLoaderRoute: typeof BriefingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals/$itemId': {
      id: '/signals/$itemId'
      path: '/signals/$itemId'
      fullPath: '/signals/$itemId'
      preLoaderRoute: typeof SignalsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/$digestId': {
      id: '/briefings/$digestId'
      path: '/briefings/$digestId'
      fullPath: '/briefings/$digestId'
      preLoaderRoute: typeof BriefingsDigestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items': {
      id: '/api/items'
      path: '/api/items'
      fullPath: '/api/items'
      preLoaderRoute: typeof ApiItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digests': {
      id: '/api/digests'
      path: '/api/digests'
      fullPath: '/api/digests'
      preLoaderRoute: typeof ApiDigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/$id': {
      id: '/api/items/$id'
      path: '/$id'
      fullPath: '/api/items/$id'
      preLoaderRoute: typeof ApiItemsIdRouteImport
      parentRoute: typeof ApiItemsRoute
    }
    '/api/digests/$id': {
      id: '/api/digests/$id'
      path: '/$id'
      fullPath: '/api/digests/$id'
      preLoaderRoute: typeof ApiDigestsIdRouteImport
      parentRoute: typeof ApiDigestsRoute
    }
  }
}

interface ApiDigestsRouteChildren {
  ApiDigestsIdRoute: typeof ApiDigestsIdRoute
}

const ApiDigestsRouteChildren: ApiDigestsRouteChildren = {
  ApiDigestsIdRoute: ApiDigestsIdRoute,
}

const ApiDigestsRouteWithChildren = ApiDigestsRoute._addFileChildren(
  ApiDigestsRouteChildren,
)

interface ApiItemsRouteChildren {
  ApiItemsIdRoute: typeof ApiItemsIdRoute
}

const ApiItemsRouteChildren: ApiItemsRouteChildren = {
  ApiItemsIdRoute: ApiItemsIdRoute,
}

const ApiItemsRouteWithChildren = ApiItemsRoute._addFileChildren(
  ApiItemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDigestsRoute: ApiDigestsRouteWithChildren,
  ApiItemsRoute: ApiItemsRouteWithChildren,
  BriefingsDigestIdRoute: BriefingsDigestIdRoute,
  SignalsItemIdRoute: SignalsItemIdRoute,
  BriefingsIndexRoute: BriefingsIndexRoute,
  SignalsIndexRoute: SignalsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
